apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: test-dns
  namespace: kube-system
  labels:
    k8s-app: test-dns
spec:
  selector:
    matchLabels:
      name: test-dns
  template:
    metadata:
      labels:
        name: test-dns
    spec:
      containers:
      - name: test-dns
        image: radial/busyboxplus:curl
        command:
          - sleep
          - "3600"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists

