apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: kube-dns
  name: kube-dns
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-dns
  labels:
    k8s-app: kube-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kube-dns
  namespace: kube-system

